version: "3.8"

services:
  notifications_ms:
    container_name: notification_ms 
    image: notification_ms_img 
    build:
      context: .
      target: notification_ms
      dockerfile: ./Dockerfile
    env_file:
      - docker.env
    ports:
      - 8888:8888
    networks:
      - medisync-notification-network
    restart: unless-stopped


networks:
  medisync-notification-network: